{
  "name": "tokenize-ai-simple",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "npx serve -s . -p $PORT",
    "prebuild": "npm install --legacy-peer-deps",
    "build": "echo 'Build completed'"
  },
  "dependencies": {
    "serve": "^14.2.0"
  }
}
